feat: choose point on map for events
uniconnect-epfl/uniconnect pull request #188
Opened 2024-05-13 19:37 UTC by GaelCondeLosada

# What I did

# How I did it

# How to verify it

# Demo video

# Pre-merge checklist
The changes I have introduced:
- [ ] work correctly
- [ ] do not break other functionalities
- [ ] work correctly on Android
- [ ] are fully tested

2024-05-14 08:35 UTC, alexandre-mrt requested changes
Just a reminder to delete the log. Otherwise LGTM

2024-05-14 08:35 UTC, alexandre-mrt commented on screens/EventCreation/EventCreationScreen.tsx
> +                console.log("going to select a location")
If it's working fine you can remove it.

2024-05-14 08:35 UTC, alexandre-mrt commented on screens/SelectLocation/SelectLocationScreen.tsx
> +                console.log("going back to precedent screen")
Delete if everything is working please. The console can be un-readable otherwise.

2024-05-15 08:48 UTC, alexandre-mrt approved these changes
LGTM

2024-05-15 09:32 UTC, AlbertoCentonze reviewed
Hey Gael, thanks for the PR! Can you help me understand why you passed navigation as a prop instead of using the hook as we were doing before?

Also I saw managed to pass functions through `navigate` which I couldn't do before, is it for this reason that you passed navigation as a prop?

2024-05-15 11:39 UTC, merged