Create friend links between users - 181
uniconnect-epfl/uniconnect pull request #193
Opened 2024-05-15 17:09 UTC by Fyuryy

# What I did
Created functions to add and remove friends 

# How I did it
Modified the user file to create the new two functions. Linked the functions to the place where they have to be called in ExternalProfileScreen and tested the globality of the code. 

# How to verify it
Try to add and/or remove a friend in your profile

# Demo video
In the making...

# Pre-merge checklist
The changes I have introduced:
- [ ] work correctly
- [ ] do not break other functionalities
- [ ] work correctly on Android
- [ ] are fully tested

2024-05-16 20:00 UTC, GustaveCharles requested changes
LGTM.However, I have not been able to test the functionalities of the PR so I cannot approve it yet.

2024-05-16 21:41 UTC, Fyuryy commented on __test__/screens/QrScan/QrScanScreen.test.tsx
Yes indeed. There was a wild "console.log(...)" that made all tests fail. I had to capture it!

2024-05-16 21:41 UTC, Fyuryy commented on __test__/firebase/User.test.ts
Thanks!

2024-05-16 21:41 UTC, Fyuryy commented on screens/Profile/ExternalProfileScreen/ExternalProfileScreen.tsx
I don't think I have understood your comment... what exactly do you mean?

2024-05-17 10:37 UTC, GustaveCharles approved these changes

2024-05-17 10:47 UTC, merged