fix: fixed profile layout
uniconnect-epfl/uniconnect pull request #243
Opened 2024-05-24 10:17 UTC by GaelCondeLosada

# What I did
Fixed the broken profile layout.

# How I did it
Modified existing style and profile files.

# How to verify it
Test it on expo go.

# Demo 

# Pre-merge checklist
The changes I have introduced:
- [ ] work correctly
- [ ] do not break other functionalities
- [ ] work correctly on Android
- [ ] are fully tested

2024-05-26 12:06 UTC, Aidasvenc commented on screens/Profile/MyProfileScreen/MyProfileScreen.tsx
> -        </View>
This should not have been done, we still need a back button :(

2024-05-26 12:07 UTC, Aidasvenc requested changes
We need the back button back. Otherwise, looks good!

2024-05-26 18:20 UTC, GaelCondeLosada commented
> We need the back button back. Otherwise, looks good!

You're right, it should be all good now!

2024-05-27 16:42 UTC, Aidasvenc approved these changes
LGTM now!

2024-05-28 09:24 UTC, merged