Setup end to end
uniconnect-epfl/uniconnect pull request #66
Opened 2024-04-12 16:08 UTC by GustaveCharles

### What I did

- Setup a framework for end to end tests. 
- Setup EAS build environment.

### How I did it

I used the new Maestro framework. You can find the docs with [this link ](https://maestro.mobile.dev/ ). To make Maestro work you need to have an emulator. For this PR and for our actual eas.json, only an Android emulator works. You can setup Expo Orbit to manage emulators on [this link](https://docs.expo.dev/build/orbit/)

### What it looks like

https://github.com/uniconnect-epfl/uniconnect/assets/91184289/c28448a0-05e9-4bf9-a02e-98467b8ecf64

2024-04-12 21:08 UTC, alexandre-mrt commented
LGTM.

2024-04-12 21:09 UTC, alexandre-mrt commented
LGTM

2024-04-12 21:45 UTC, Aidasvenc requested changes
Everything looks good except that I think the .apk itself is not needed

2024-04-12 21:45 UTC, Aidasvenc commented on uni-connect-v0.apk
I don't think we should push this file into main

2024-04-13 12:23 UTC, Aidasvenc commented on uni-connect-v0.apk
Refactored!

2024-04-13 12:25 UTC, Aidasvenc approved these changes
LGTM now!

2024-04-13 12:25 UTC, merged